[package]
name = "nixon"
description = "Project environment and command launcher"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
comrak.workspace = true
crossterm.workspace = true
etcetera.workspace = true
glob.workspace = true
sha1.workspace = true
shell-words.workspace = true
signal-hook.workspace = true
shellexpand.workspace = true
nixon-picker.workspace = true
serde.workspace = true
serde-saphyr.workspace = true
serde_json.workspace = true
thiserror.workspace = true
winnow.workspace = true

[features]
test-util = ["nixon-picker/test-util"]

[dev-dependencies]
assert_fs.workspace = true
nixon-picker = { workspace = true, features = ["test-util"] }
proptest.workspace = true
rstest.workspace = true

[lints]
workspace = true
