[package]
name = "nixon-cli"
description = "Command-line interface for nixon"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "nixon"
path = "src/main.rs"

[dependencies]
clap.workspace = true
clap_complete.workspace = true
nixon.workspace = true
nixon-picker.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
assert_fs.workspace = true
insta.workspace = true
predicates.workspace = true

[lints]
workspace = true
