[package]
name = "nixon-cli"
description = "Command-line interface for nixon"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "nixon"
path = "src/main.rs"

[dependencies]
clap.workspace = true
clap_complete.workspace = true
clap_mangen.workspace = true
eframe.workspace = true
nixon.workspace = true
nixon-gui.workspace = true
nixon-picker.workspace = true
serde_json.workspace = true
tempfile.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
zbus = "4.4"

[dev-dependencies]
assert_cmd.workspace = true
assert_fs.workspace = true
expectrl.workspace = true
insta.workspace = true
predicates.workspace = true

[lints]
workspace = true
