[package]
name = "nixon-gui"
description = "Graphical menu state for Nixon"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
eframe.workspace = true
nixon.workspace = true
nixon-picker.workspace = true

[lints]
workspace = true
